// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyXrl00z4uD0a61HtGBgHp841OarumvUo',
    appId: '1:198014969028:web:cee2cde7dd64caf0949591',
    messagingSenderId: '198014969028',
    projectId: 'rmsa-bc6bb',
    authDomain: 'rmsa-bc6bb.firebaseapp.com',
    storageBucket: 'rmsa-bc6bb.firebasestorage.app',
    measurementId: 'G-RXQ7TMRJGS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTynZ58_ar--asBkbR-qiJwePmubJ2yxA',
    appId: '1:198014969028:android:d08fa9f2bd46bde1949591',
    messagingSenderId: '198014969028',
    projectId: 'rmsa-bc6bb',
    storageBucket: 'rmsa-bc6bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFTa9uXHuQL1ooQpom5NPK5peSqboLTfY',
    appId: '1:198014969028:ios:fa08e84da32c8e6e949591',
    messagingSenderId: '198014969028',
    projectId: 'rmsa-bc6bb',
    storageBucket: 'rmsa-bc6bb.firebasestorage.app',
    androidClientId: '198014969028-7erqcstn9e7u91uasarjed2a3v4romu0.apps.googleusercontent.com',
    iosClientId: '198014969028-onmkgpour1ed8d90mjr74031it6paon9.apps.googleusercontent.com',
    iosBundleId: 'com.example.rmsadash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFTa9uXHuQL1ooQpom5NPK5peSqboLTfY',
    appId: '1:198014969028:ios:fa08e84da32c8e6e949591',
    messagingSenderId: '198014969028',
    projectId: 'rmsa-bc6bb',
    storageBucket: 'rmsa-bc6bb.firebasestorage.app',
    androidClientId: '198014969028-7erqcstn9e7u91uasarjed2a3v4romu0.apps.googleusercontent.com',
    iosClientId: '198014969028-onmkgpour1ed8d90mjr74031it6paon9.apps.googleusercontent.com',
    iosBundleId: 'com.example.rmsadash',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyXrl00z4uD0a61HtGBgHp841OarumvUo',
    appId: '1:198014969028:web:82cfaf0f1beb2b44949591',
    messagingSenderId: '198014969028',
    projectId: 'rmsa-bc6bb',
    authDomain: 'rmsa-bc6bb.firebaseapp.com',
    storageBucket: 'rmsa-bc6bb.firebasestorage.app',
    measurementId: 'G-9T6P8GDJT3',
  );
}
